name: immutable_collection
description: Immutable collections, IList<E>, ISet<E>, IMap<K, V>. They all compare as value types.
version: 0.2.0
homepage: https://github.com/vr19860507/immutable_collection

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  meta: ^1.0.0
  collection: ^1.0.0

dev_dependencies:
  strict_analyzer: ^0.4.0